modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "leawind_third_person_perspective"
version = "${version}"
displayName = "LEAWIND's Third Person Perspective"
authors = "LEAWIND"
description = '''
	Mutch better third person perspective
'''
#logoFile = ""

[[dependencies.leawind_third_person_perspective]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.leawind_third_person_perspective]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.leawind_third_person_perspective]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
